import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('testuser');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Password@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div').filter({ hasText: /^Hyderabad$/ }).nth(4).click();
  await page.getByRole('link', { name: 'Training Manage training' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Training Manage training' }).click();
  await page.getByLabel('Breadcrumb').getByText('Training').click();
  await page.getByRole('link', { name: '3 Active Assignments Manage' }).click();
  await page.getByText('152', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^10$/ }).click();
  await page.getByText('In Progress142').click();
  await page.locator('div').filter({ hasText: /^Completed$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Overdue$/ }).first().click();
  await page.getByRole('textbox', { name: 'Search by training title,' }).click();
  await page.getByRole('textbox', { name: 'Search by training title,' }).fill('t');
  await page.goto('http://localhost:3000/training');
  await page.getByRole('link', { name: '3 Active Assignments Manage' }).click();
  await page.getByRole('textbox', { name: 'Search by training title,' }).click();
  await page.getByRole('textbox', { name: 'Search by training title,' }).fill('t');
  await page.getByRole('combobox').first().selectOption('active');
  await page.getByRole('combobox').first().selectOption('overdue');
  await page.getByRole('combobox').first().selectOption('expired');
  await page.getByRole('combobox').first().selectOption('active');
  await page.getByRole('combobox').nth(1).selectOption('Course');
  await page.getByRole('combobox').nth(1).selectOption('Curriculum');
  await page.getByRole('textbox', { name: 'Search by training title,' }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.getByRole('columnheader', { name: 'Level' }).click();
  await page.getByRole('columnheader', { name: 'Level' }).click();
  await page.getByRole('columnheader', { name: 'Priority' }).click();
  await page.getByRole('columnheader', { name: 'Assigned Date' }).nth(1).click();
  await page.getByRole('columnheader', { name: 'Assigned Date' }).nth(1).click();
  await page.getByRole('columnheader', { name: 'Status' }).click();
  await page.getByRole('button', { name: 'Stop' }).nth(2).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Abort Training' }).first().click();
  await page.getByRole('textbox', { name: 'Enter the reason for aborting…' }).click();
  await page.getByRole('textbox', { name: 'Enter the reason for aborting…' }).fill('test');
  await page.getByRole('textbox', { name: 'Type your full name' }).click();
  await page.getByRole('textbox', { name: 'Type your full name' }).fill('Gopisetty Jaswanth');
  await page.getByRole('textbox', { name: 'Type your full name' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Type your full name' }).press('ControlOrMeta+c');
  await page.getByRole('button', { name: 'Confirm Abort' }).click();
  await page.getByRole('combobox').first().selectOption('all');
  await page.getByRole('textbox', { name: 'Search by training title,' }).click();
  await page.getByRole('textbox', { name: 'Search by training title,' }).fill('a');
  await page.getByRole('link', { name: '3 Active Assignments Manage' }).click();
});
