import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('testuser');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Password@123');
  await page.getByText('UserNamePasswordForgot password?Sign InNew to QMS?Create an AccountSystem').click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('main').getByText('Hyderabad').click();
  await page.getByRole('link', { name: 'Training Manage training' }).click();
  await page.getByRole('link', { name: '8 Sessions Calendar Schedule' }).click();
  await page.getByText('All Month (December 1 – 31)').click();
  await page.getByText('All Month (December 1 – 31)').nth(1).click();
  await page.locator('div').filter({ hasText: /^DateMonday, December 1, 2025All Month \(December 1 – 31\)$/ }).first().click();
  await page.locator('div').filter({ hasText: /^TrainerAnnual Plan$/ }).first().click();
  await page.locator('div').filter({ hasText: /^LocationPlanned$/ }).first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: /^2$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^2$/ }).first().click();
  await page.locator('div').filter({ hasText: /^3$/ }).first().click();
  await page.locator('div').filter({ hasText: /^4$/ }).first().click();
  await page.locator('div:nth-child(2) > button:nth-child(3)').click();
  await page.locator('div:nth-child(2) > button:nth-child(3)').click();
  await page.locator('div:nth-child(2) > button:nth-child(3)').dblclick();
  await page.locator('.p-2.hover\\:bg-slate-100').first().dblclick();
  await page.locator('.p-2.hover\\:bg-slate-100').first().click();
  await page.locator('.p-2.hover\\:bg-slate-100').first().click();
  await page.getByRole('button', { name: 'Day' }).click();
  await page.getByRole('button', { name: 'Week' }).click();
  await page.getByRole('button', { name: 'Month' }).click();
  await page.getByRole('textbox', { name: 'Jump to date' }).fill('2017-01-04');
  await page.getByRole('button', { name: 'All Tasks' }).click();
  await page.getByRole('button', { name: 'All Tasks' }).click();
  await page.getByRole('button', { name: 'Role Task' }).click();
  await page.getByRole('button', { name: 'Individual Task' }).click();
  await page.getByText('Non-Blocking Calendar').click();
  await page.getByRole('button', { name: 'Show Annual Plan' }).click();
  await page.getByText('GMP Basics').click();
  await page.getByText('Safety Training✓ CompletedView Details').click();
  await page.getByText('GMP Basics✓ CompletedView').click();
  await page.getByText('GMP Basics✓ CompletedView').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: /^Safety Training$/ }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.getByRole('button', { name: 'Close' }).nth(1).click();
  await page.getByRole('button', { name: 'Remove' }).first().click();
  await page.getByRole('textbox', { name: 'Enter your password to confirm' }).click();
  await page.getByRole('textbox', { name: 'Enter your password to confirm' }).fill('test');
  await page.getByRole('button', { name: 'Confirm Removal' }).click();
  await page.getByRole('button', { name: 'Remove' }).first().click();
  await page.getByRole('textbox', { name: 'Enter your password to confirm' }).click();
  await page.getByRole('textbox', { name: 'Enter your password to confirm' }).fill('c');
  await page.getByRole('button', { name: 'Confirm Removal' }).click();
  await page.getByRole('button', { name: 'Add Training / Curriculum' }).click();
  await page.getByText('GMP Fundamentals').click();
  await page.getByRole('button', { name: 'Next: Assign' }).click();
  await page.locator('div').filter({ hasText: /^Quality Assurance$/ }).first().click();
  await page.getByRole('button', { name: 'Roles' }).click();
  await page.getByRole('button', { name: 'Roles' }).click();
  await page.locator('div').filter({ hasText: /^QA Manager$/ }).first().click();
  await page.getByRole('button', { name: 'Individuals' }).click();
  await page.locator('.w-5.h-5.rounded-md').first().click();
  await page.locator('.w-5.h-5.rounded-md.border-2.flex.items-center.justify-center.transition-colors.border-slate-300').first().click();
  await page.locator('.w-5.h-5.rounded-md.border-2.flex.items-center.justify-center.transition-colors.border-slate-300').first().click();
  await page.getByRole('button', { name: 'Roles' }).click();
  await page.locator('div').filter({ hasText: /^QC Analyst$/ }).first().click();
  await page.locator('.w-5.h-5.rounded-md.border-2.flex.items-center.justify-center.transition-colors.border-slate-300').first().click();
  await page.getByRole('button', { name: 'Departments' }).click();
  await page.locator('.w-5.h-5.rounded-md.border-2.flex.items-center.justify-center.transition-colors.border-slate-300').first().click();
  await page.locator('div').filter({ hasText: /^Production$/ }).first().click();
  await page.locator('.w-5.h-5.rounded-md.border-2.flex.items-center.justify-center.transition-colors.border-slate-300').first().click();
  await page.getByRole('button', { name: 'Roles' }).click();
  await page.getByRole('button', { name: 'Individuals' }).click();
  await page.getByText('ECEmily ChenR&D • Lab').click();
  await page.getByRole('button', { name: 'Groups' }).click();
  await page.locator('div').filter({ hasText: /^Lab Personnel8 members$/ }).first().click();
  await page.locator('div').filter({ hasText: /^New Joiners 20265 members$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Supervisors6 members$/ }).nth(1).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Add & Assign (1)' }).click();
  await page.locator('.text-white\\/80').click();
  await page.getByRole('combobox').selectOption('2025');
  await page.getByText('January 2017').click();
  await page.getByText('January 2017').click();
  await page.getByRole('textbox', { name: 'Jump to date' }).fill('2026-06-04');
  await page.locator('.flex-1.pb-1').first().click();
  await page.locator('.space-y-0\\.5 > div:nth-child(2) > .flex-1').click();
  await page.getByRole('button', { name: 'Hide Annual Plan' }).click();
  await page.getByRole('button', { name: 'Role Task' }).click();
  await page.getByRole('button', { name: 'Individual Task' }).click();
  await page.getByRole('button', { name: 'All Tasks' }).click();
  await page.getByRole('link', { name: 'Training' }).nth(4).click();
});
