import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'UserName' }).click();
  await page.getByRole('textbox', { name: 'UserName' }).fill('testuser');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Password@123');
  await page.locator('.absolute.right-3').click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Horizontal' }).click();
  await page.getByRole('button', { name: 'Vertical' }).click();
  await page.locator('.w-5.h-5.text-slate-700').click();
  await page.locator('.w-5.h-5.text-slate-700').click();
  await page.locator('.relative.p-4.bg-white.rounded-md.shadow-md.hover\\:shadow-lg.transition-all.cursor-pointer.border-2.min-w-\\[250px\\].border-green-500 > .flex.items-center.justify-between > .flex-1 > .flex').click();
  await page.getByRole('link', { name: 'Training Manage training' }).click();
  await page.getByRole('link', { name: 'Active Classroom Manage' }).click();
  await page.getByRole('textbox', { name: 'Search by title, code, or' }).click();
  await page.getByRole('textbox', { name: 'Search by title, code, or' }).fill('');
  await page.getByRole('button', { name: 'Filters (5 available)' }).click();
  await page.getByRole('button', { name: 'All Status 5 options' }).click();
  await page.getByRole('button', { name: 'Scheduled' }).click();
  await page.getByRole('button', { name: '×' }).click();
  await page.getByRole('button', { name: 'Filters (5 available)' }).click();
  await page.getByRole('button', { name: 'All Status 5 options' }).click();
  await page.getByRole('button', { name: '← Back to filters' }).click();
  await page.locator('div').filter({ hasText: 'Training/Training' }).nth(4).click();
  await page.getByText('Select Filter×').click();
  await page.getByRole('button', { name: '×' }).click();
  await page.goto('http://localhost:3000/training/sessions');
  await page.getByRole('button', { name: 'Filters (5 available)' }).click();
  await page.getByRole('button', { name: 'All Status 5 options' }).click();
  await page.getByRole('button', { name: 'Draft' }).click();
  await page.getByRole('button', { name: 'Filters (4 available)' }).click();
  await page.getByRole('button', { name: 'All Categories 4 options' }).click();
  await page.getByRole('button', { name: 'ILT', exact: true }).click();
  await page.getByRole('button', { name: 'Filters (3 available)' }).click();
  await page.getByRole('button', { name: 'All Departments 4 options' }).click();
  await page.getByRole('button', { name: 'Quality Assurance' }).click();
  await page.getByRole('button', { name: 'Filters (2 available)' }).click();
  await page.getByRole('button', { name: 'All Types 4 options' }).click();
  await page.getByText('← Back to filtersSelect All').click();
  await page.getByRole('button', { name: 'Filters (1 available)' }).click();
  await page.getByRole('button', { name: 'All Groups 5 options' }).click();
  await page.getByRole('button', { name: 'Quality Assurance' }).click();
  await page.getByRole('button', { name: 'Clear all' }).click();
  await page.getByText('Scheduled').click();
  await page.getByRole('textbox', { name: 'Search by title, code, or' }).click();
  await page.getByRole('textbox', { name: 'Search by title, code, or' }).fill('');
  await page.getByRole('button', { name: 'Create Classroom' }).click();
  await page.getByRole('textbox', { name: 'Search by training title or' }).click();
  await page.getByText('GMP Fundamentals Training').click();
  await page.getByText('Comprehensive training on').click();
  await page.getByText('Comprehensive training on').click();
  await page.getByText('Comprehensive training on').click();
  await page.getByText('Comprehensive training on').click();
  await page.getByText('Comprehensive training on').click();
  await page.locator('div').filter({ hasText: /^Select trainers\.\.\.$/ }).nth(1).click();
  await page.getByText('Comprehensive training on').click();
  await page.locator('div').filter({ hasText: /^Select trainers\.\.\.$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Select trainers\.\.\.$/ }).click();
  await page.getByText('Select Trainer(s) *Select').click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).fill('mike');
  await page.locator('.w-4.h-4.rounded').click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).fill('john');
  await page.locator('div:nth-child(2) > .w-4').click();
  await page.locator('.w-4.h-4.rounded').first().click();
  await page.locator('span:nth-child(2) > .ml-0\\.5').click();
  await page.getByText('Mike Davis').click();
  await page.locator('.ml-0\\.5').first().click();
  await page.locator('div').filter({ hasText: /^John Smith$/ }).nth(1).click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).click();
  await page.locator('div').filter({ hasText: /^Sarah JohnsonEMP-TR-002$/ }).first().click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).fill('mike');
  await page.locator('.w-4.h-4.rounded').click();
  await page.getByRole('button', { name: 'Clear all' }).click();
  await page.locator('.w-4.h-4.rounded').click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).fill('john');
  await page.locator('.w-4.h-4.rounded').first().click();
  await page.locator('.w-4.h-4.rounded.border.flex.items-center.justify-center.flex-shrink-0.border-gray-300').click();
  await page.getByText('Select Training *Training').click();
  await page.getByRole('button', { name: '+ Add Session' }).click();
  await page.getByRole('textbox', { name: 'https://meet.example.com/' }).click();
  await page.getByRole('textbox', { name: 'https://meet.example.com/' }).fill('test.com');
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').fill('202222-01-02T11:11');
  await page.getByText('Session 1Meeting Platform *').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').click();
  await page.locator('input[type="datetime-local"]').press('ArrowRight');
  await page.locator('input[type="datetime-local"]').press('ArrowRight');
  await page.locator('input[type="datetime-local"]').press('ArrowRight');
  await page.locator('input[type="datetime-local"]').press('ArrowLeft');
  await page.locator('input[type="datetime-local"]').fill('2026-01-02T11:11');
  await page.getByPlaceholder('60').click();
  await page.getByPlaceholder('60').fill('2');
  await page.getByRole('button', { name: 'Mike Davis' }).click();
  await page.getByRole('button', { name: 'John Smith' }).click();
  await page.getByRole('button', { name: 'Sarah Johnson' }).click();
  await page.getByRole('button', { name: 'Mike Davis' }).click();
  await page.getByRole('button', { name: 'John Smith' }).click();
  await page.getByRole('button', { name: 'Sarah Johnson' }).click();
  await page.getByRole('button', { name: 'Assign User' }).click();
  await page.getByRole('button', { name: 'Select Departments' }).click();
  await page.locator('label').filter({ hasText: 'General' }).click();
  await page.getByRole('textbox', { name: 'Search users...' }).click();
  await page.getByRole('textbox', { name: 'Search users...' }).fill('jaswanth');
  await page.getByRole('textbox', { name: 'Search users...' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Search users...' }).fill('');
  await page.getByRole('button', { name: 'Select Departments' }).click();
  await page.getByRole('checkbox', { name: 'General' }).uncheck();
  await page.locator('div').filter({ hasText: /^Search$/ }).click();
  await page.getByRole('textbox', { name: 'Search users...' }).click();
  await page.getByRole('textbox', { name: 'Search users...' }).fill('john');
  await page.getByRole('checkbox', { name: 'Eve Johnson eve.johnson@' }).check();
  await page.getByRole('textbox', { name: 'Search users...' }).click();
  await page.getByRole('textbox', { name: 'Search users...' }).fill('martin');
  await page.getByRole('checkbox', { name: 'Bob Martin bob.martin@company' }).check();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Schedule Classroom' }).click();
  await page.locator('span').filter({ hasText: 'Mike Davis' }).click();
  await page.getByRole('button', { name: 'John Smith' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Schedule Classroom' }).click();
  await page.getByText('Trainer is mandatory for').click();
  await page.getByText('Mike DavisJohn SmithSarah').first().click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).click();
  await page.getByRole('textbox', { name: 'Search trainers...' }).fill('');
  await page.locator('.w-4.h-4.rounded.border.flex.items-center.justify-center.flex-shrink-0.border-gray-300').first().click();
  await page.locator('.w-4.h-4.rounded.border.flex.items-center.justify-center.flex-shrink-0.border-gray-300').click();
  await page.getByText('Start Date & Time').click();
  await page.getByRole('button', { name: 'Sarah Johnson' }).click();
  await page.getByRole('button', { name: 'Emily Brown' }).click();
  await page.getByRole('button', { name: 'David Wilson' }).click();
  await page.getByRole('button', { name: 'Save as Draft' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Update Classroom (2 Sessions)' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Update Classroom (2 Sessions)' }).click();
  await page.locator('.w-full.min-h-\\[42px\\]').click();
  await page.locator('div').filter({ hasText: /^John SmithEMP-TR-001$/ }).first().click();
  await page.locator('div').filter({ hasText: /^John SmithEMP-TR-001$/ }).first().click();
  await page.locator('div').filter({ hasText: /^John SmithEMP-TR-001$/ }).first().click();
  await page.locator('.w-4.h-4.rounded.border.flex.items-center.justify-center.flex-shrink-0.border-gray-300').first().click();
  await page.locator('.w-4.h-4.rounded.border.flex.items-center.justify-center.flex-shrink-0.border-gray-300').first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Update Classroom (2 Sessions)' }).click();
  await page.getByText('CancelUpdate Classroom (2').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Attendance' }).click();
  await page.getByRole('button', { name: 'Documentation & Deviation' }).click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('button', { name: 'Reassign to another session' }).first().click();
  await page.getByRole('button', { name: 'Reassign to another session' }).first().click();
  await page.getByRole('button', { name: 'Remove from session' }).first().click();
  await page.getByRole('button', { name: 'Remove Participant' }).click();
  await page.getByRole('button', { name: 'Remove from session' }).nth(1).click();
  await page.getByRole('button', { name: 'Remove Participant' }).click();
  await page.locator('.sticky > .flex').click();
  await page.locator('.text-gray-400.hover\\:text-gray-600').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.locator('.p-2.hover\\:bg-gray-100.rounded-lg').click();
  await page.getByRole('button', { name: 'View Details' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Archive' }).click();
  await page.getByRole('button', { name: 'Archive Classroom' }).click();
  await page.getByRole('button', { name: 'Filters (5 available)' }).click();
  await page.getByRole('button', { name: 'All Status 5 options' }).click();
  await page.getByRole('button', { name: '← Back to filters' }).click();
  await page.getByRole('button', { name: 'All Types 4 options' }).click();
  await page.getByRole('button', { name: '← Back to filters' }).click();
  await page.getByRole('button', { name: 'All Categories 4 options' }).click();
  await page.getByRole('button', { name: '← Back to filters' }).click();
  await page.getByRole('button', { name: 'All Status 5 options' }).click();
  await page.locator('div').filter({ hasText: 'Training/Training' }).nth(4).click();
  await page.getByRole('button', { name: '← Back to filters' }).click();
  await page.locator('div').filter({ hasText: 'Training/Training' }).nth(4).click();
  await page.getByRole('button', { name: '×' }).click();
  await page.getByRole('button', { name: 'Export' }).click();
});
